#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Splash

#include "Basic.hpp"

#include "Splash_classes.hpp"
#include "Splash_parameters.hpp"


namespace SDK
{

// Function Splash.Splash_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASplash_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Splash_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Splash.Splash_C.êšI‹ö_0
// (BlueprintCallable, BlueprintEvent)

void ASplash_C::__I___0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Splash_C", "êšI‹ö_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Splash.Splash_C.êšI‹ö_1
// (BlueprintCallable, BlueprintEvent)

void ASplash_C::__I___1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Splash_C", "êšI‹ö_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Splash.Splash_C.ExecuteUbergraph_Splash
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASplash_C::ExecuteUbergraph_Splash(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Splash_C", "ExecuteUbergraph_Splash");

	Params::Splash_C_ExecuteUbergraph_Splash Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

