#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Splash_0

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Splash.Splash
// 0x0018 (0x0018 - 0x0000)
struct FSplash final
{
public:
	class UTexture2D*                             Value_3_0D5C89D24C7243E14F07EF81CAA61C07;          // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 Path_6_6E4D30EE47AF016A024B5FB55CEF5DAC;           // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(FSplash) == 0x000008, "Wrong alignment on FSplash");
static_assert(sizeof(FSplash) == 0x000018, "Wrong size on FSplash");
static_assert(offsetof(FSplash, Value_3_0D5C89D24C7243E14F07EF81CAA61C07) == 0x000000, "Member 'FSplash::Value_3_0D5C89D24C7243E14F07EF81CAA61C07' has a wrong offset!");
static_assert(offsetof(FSplash, Path_6_6E4D30EE47AF016A024B5FB55CEF5DAC) == 0x000008, "Member 'FSplash::Path_6_6E4D30EE47AF016A024B5FB55CEF5DAC' has a wrong offset!");

}

