#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TapLogin

#include "Basic.hpp"


namespace SDK::Params
{

// Function TapLogin.TULoginReflection.GetOpenID
// 0x0010 (0x0010 - 0x0000)
struct TULoginReflection_GetOpenID final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(TULoginReflection_GetOpenID) == 0x000008, "Wrong alignment on TULoginReflection_GetOpenID");
static_assert(sizeof(TULoginReflection_GetOpenID) == 0x000010, "Wrong size on TULoginReflection_GetOpenID");
static_assert(offsetof(TULoginReflection_GetOpenID, ReturnValue) == 0x000000, "Member 'TULoginReflection_GetOpenID::ReturnValue' has a wrong offset!");

}

