#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TapLogin

#include "Basic.hpp"

#include "TapLogin_classes.hpp"
#include "TapLogin_parameters.hpp"


namespace SDK
{

// Function TapLogin.TULoginReflection.GetOpenID
// (Final, Native, Static, Private)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UTULoginReflection::GetOpenID()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("TULoginReflection", "GetOpenID");

	Params::TULoginReflection_GetOpenID Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

