#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TapUpdate

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class TapUpdate.TapUpdateStaticLibrary
// 0x0000 (0x0030 - 0x0030)
class UTapUpdateStaticLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void Init(const class FString& ClientId, const class FString& ClientToken);
	static void UpdateGame(TDelegate<void()> Handle);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TapUpdateStaticLibrary">();
	}
	static class UTapUpdateStaticLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTapUpdateStaticLibrary>();
	}
};
static_assert(alignof(UTapUpdateStaticLibrary) == 0x000008, "Wrong alignment on UTapUpdateStaticLibrary");
static_assert(sizeof(UTapUpdateStaticLibrary) == 0x000030, "Wrong size on UTapUpdateStaticLibrary");

}

