#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TapUpdate

#include "Basic.hpp"

#include "TapUpdate_classes.hpp"
#include "TapUpdate_parameters.hpp"


namespace SDK
{

// Function TapUpdate.TapUpdateStaticLibrary.Init
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class FString                           ClientId                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           ClientToken                                            (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UTapUpdateStaticLibrary::Init(const class FString& ClientId, const class FString& ClientToken)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("TapUpdateStaticLibrary", "Init");

	Params::TapUpdateStaticLibrary_Init Parms{};

	Parms.ClientId = std::move(ClientId);
	Parms.ClientToken = std::move(ClientToken);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TapUpdate.TapUpdateStaticLibrary.UpdateGame
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// TDelegate<void()>                       Handle                                                 (Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)

void UTapUpdateStaticLibrary::UpdateGame(TDelegate<void()> Handle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("TapUpdateStaticLibrary", "UpdateGame");

	Params::TapUpdateStaticLibrary_UpdateGame Parms{};

	Parms.Handle = Handle;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

