#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsSplash

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsSplash.TsSplash_C
// 0x0000 (0x0030 - 0x0030)
class UTsSplash_C final : public UObject
{
public:
	void Init(class UObject* WorldContext);
	void ShowSplashView();
	void ChangeToPhaseShaderBlack();
	void ChangeToPhaseThree();
	void ChangeToPhaseTwo();
	void LoopEvent(float Gap, bool* FinishLoopState);
	void ChangeScene();
	float GetDelay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TsSplash_C">();
	}
	static class UTsSplash_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsSplash_C>();
	}
};
static_assert(alignof(UTsSplash_C) == 0x000008, "Wrong alignment on UTsSplash_C");
static_assert(sizeof(UTsSplash_C) == 0x000030, "Wrong size on UTsSplash_C");

}

